### ISSUE TITLE
Is this the future of the mandango code?

### ISSUE THREAD

**Issue by jrschumacher** [mongator/mongator#13]

**Comment by mcuadros** [comment]
Hi Ryan,

The original project looks like abandoned. 

In our company we are using in production the mongator fork and we will continue supporting and adding new features.

We already made several changes internals but has basicaly the same features and interface.

We are working on complete the documentation with the new features and documention site.

The last tag is a stable version

Regards and thanks.

**Comment by jrschumacher** [comment]
Oh that is fantastic news!

Side question, does your documentation talk about use of embeddeds, we have been having some issues and mandango documentation doesn't seem to talk about queries with embeddeds?

**Comment by mcuadros** [comment]
You want to query to embeddedGroups? or just query a collection by the
embedded?

Explain me a little more your problem, please

**Comment by wildsurfer** [comment]
Hi mcuadros

Ryan is talking about this situation:

Let's say we have this schema

``` php
// Model\User.php
return array(
    'fields' => array(
        'email' => array(
            'type' => 'string',
            'dbName' => 'email'
        ),
    ),
    'embeddedsMany' => array(
        'phone' => array('class' => 'Model\Phone'),
    ),
);
```

``` php
// Model\Phone.php
return array(
    'isEmbedded' => true,
    'fields' => array(
        'type' => 'string',
        'number' => 'string',
    ),
);
```

Let's say we need to fetch 100 users from database with their phones to get result like this:

``` php
array(
    array(email => 'test@gmail.com', 'phone' => array(array('type' => 'other', 'number' => '1234567890'), array('type' => 'other', 'number' => '1234567890'))),
    array(email => 'test1@gmail.com', 'phone' => array(array('type' => 'other', 'number' => '1234567890')))
    ....
);
```

What is a most efficient way to do this?

**Comment by mcuadros** [comment]
If i understand well your question, you want to get just the email and the phones embeddeds?

``` php
$query = $userRepository->createQuery();
$query->fields(['email' => 1, 'phone' => 1]);

$output = [];
foreach ($query->all() as $user) {
     $array = $user->toArray();
     foreach($user->getPhone() as $phone) {
          $array['phone'][] = $phone->toArray();
     }

    $output[] = $array;
}
```

This must work, but i think that is better use it as a objects instead of casting it to an array.

**Comment by wildsurfer** [comment]
Thanks for your reply. We will try it

> i think that is better use it as a objects instead of casting it to an array.

Main reason to cast it to array is because in our case it should be something we can put into JSONResponse

**Comment by mcuadros** [comment]
Oh i understand maybe you can override toArray function to include the embeddeds.

Thanks

**Comment by wildsurfer** [comment]
Override toArray seems to be a great idea, thanks!

**Comment by tacone** [comment]
Hello, excuse me for abusing this issue to pose questions, but I don't know of any other communication channel about Mongator.

I'm evaluating Mongator to develop a core product for the company I work in.
- Is Mongator still an active project?
- Is it used in production, anywhere?
- Does it make use of the aggregation framework yet?
- In the even we choose Mongator, are you open to accept contributions?

**Comment by jrschumacher** [comment]
We no longer use it in production as it didn't fit our application in it's current state. Instead we use [Purekid/mongodm](https://github.com/purekid/mongodm)

**Comment by dripolles** [comment]
Hello,

we are using Mongator in our production environment for http://yunait.com, and we actively maintain it. You don't see many changes lately because it has been very stable, but we are definitely using it everyday.

We are not using the aggregation framework yet, although if you need it you can always get to the "bare" MongoCollection from the repository and use that. Of course, if you want to contribute with code for that functionality or any other issue we are completely open for your pull requests.
